server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 741852963
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.25.140
  #消息队列
  rabbitmq:
    host: 192.168.25.140    #消息队列的地址
    username: leyou         #消息队列用户名和密码
    password: leyou
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo