server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.140
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

#pojo属性
ly:
  jwt:
    pubKeyPath: F:/a.code/ideaHome03/SpringBoot_Shopping/SBS_01/auth_rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN #cookie的的名称